### ISSUE TITLE
email pass exposed to public

### ISSUE THREAD

**Issue by beribener** [beribener/com.rightback.ChocAn#1]
email pass is exposed to public in this commit
https://github.com/beribener/com.rightback.ChocAn/commit/a3710e0002dd45cb743641c246826a8d9f2418f5

we need to move it to separate file not included in github.

**Comment by magid0780099** [comment]
I thought I made that change local. sorry for that

**Comment by magid0780099** [comment]
I moved it to seperate file and send you updated config

**Comment by beribener** [comment]
no problem thanks for update
